In [12]:
import sys
from pathlib import Path

project_python = Path.cwd().parent.resolve()

if str(project_python) not in sys.path:
    sys.path.insert(0, str(project_python))

print(project_python)

C:\Users\Welcome\Desktop\RetailIQ\Python

In [14]:
import importlib
import src.generators as generators

importlib.reload(generators)

In [5]:
generators.generate_products(5)

Groceries Amul Biscuits
Clothing Levi's Jacket
Groceries Britannia Coffee
Electronics Apple Tablet
Groceries Britannia Butter

Empty DataFrame
Columns: []
Index: []

In [13]:
products_df = generators.generate_products(10)

products_df.head()

,product_id,sku,product_name,category,brand,unit_price,cost_price,stock_quantity,reorder_level,status
0,1,CLO-000001,Jeans,Clothing,Levi's,709.60,614.30,230,49,Active
1,2,GRO-000002,Milk,Groceries,Nestle,1744.08,1425.52,37,50,Active
2,3,BOO-000003,SQL Fundamentals,Books,Pearson,1786.27,1582.50,18,18,Active
3,4,GRO-000004,Coffee,Groceries,Nestle,1997.40,1489.52,60,47,Active
4,5,ELE-000005,Smartphone,Electronics,HP,131661.20,112705.76,105,46,Active

In [22]:
products_df = generators.generate_products(100)

In [39]:
import importlib
import src.validators as validators

importlib.reload(validators)

print("✅ Validators module loaded successfully")

✅ Validators module loaded successfully

In [20]:
test_df = products_df.copy()

test_df.loc[0, "brand"] = None

validators.validate_product_missing_values(test_df)

==================================================
Product Missing Value Validation
==================================================
❌ Missing values detected:
brand    1
dtype: int64

In [23]:
test_df = products_df.copy()

test_df.loc[5,"sku"] = test_df.loc[0,"sku"]

test_df.loc[10,"product_id"] = test_df.loc[0,"product_id"]

In [24]:
validators.validate_duplicate_sku(test_df)

validators.validate_duplicate_product_id(test_df)

==================================================
Checking Duplicate SKU
❌ Duplicate SKU found
   product_id         sku product_name   category   brand  unit_price  \
5           6  CLO-000001       Butter  Groceries  Nestle     1338.62

   cost_price  stock_quantity  reorder_level  status
5     1158.76             324             40  Active
==================================================
==================================================
Checking Duplicate Product ID
❌ Duplicate product_id found
    product_id         sku product_name     category brand  unit_price  \
10           1  ELE-000011       Laptop  Electronics  Dell    94279.58

    cost_price  stock_quantity  reorder_level  status
10     66406.3             378             16  Active
==================================================

In [26]:
test_df = products_df.copy()

test_df.loc[0,"cost_price"] = 90000
test_df.loc[0,"unit_price"] = 50000

In [27]:
validators.validate_price_columns(test_df)

==================================================
Checking Price Validation
❌ Invalid price relationship found
   product_id         sku product_name  category brand  unit_price  \
0           1  CLO-000001       Hoodie  Clothing  Nike     50000.0

   cost_price  stock_quantity  reorder_level  status
0     90000.0             310             29  Active
==================================================

In [28]:
test_df = products_df.copy()

test_df.loc[0,"category"] = "Toys"

In [31]:
validators.validate_categories(test_df)

==================================================
Checking Product Categories
❌ Invalid categories found
   product_id         sku product_name category brand  unit_price  cost_price  \
0           1  CLO-000001       Hoodie     Toys  Nike     6570.24     5751.19

   stock_quantity  reorder_level  status
0             310             29  Active
==================================================

In [33]:
validators.validate_status(products_df)

==================================================
Checking Product Status
✅ All statuses are valid
==================================================

In [34]:
test_df = products_df.copy()

test_df.loc[0,"stock_quantity"] = 200
test_df.loc[0,"status"] = "Out of Stock"

In [35]:
validators.validate_status(test_df)

==================================================
Checking Product Status
❌ Invalid status found
   product_id         sku product_name  category brand  unit_price  \
0           1  CLO-000001       Hoodie  Clothing  Nike     6570.24

   cost_price  stock_quantity  reorder_level        status
0     5751.19             200             29  Out of Stock
==================================================

In [37]:
test_df = products_df.copy()

test_df.loc[0,"stock_quantity"] = -50
test_df.loc[1,"reorder_level"] = -10

In [38]:
validators.validate_stock(test_df)

==================================================
Checking Stock Validation
❌ Invalid stock values found
   product_id         sku  product_name  category    brand  unit_price  \
0           1  CLO-000001        Hoodie  Clothing     Nike     6570.24
1           2  BOO-000002  Data Science     Books  Penguin     1063.59

   cost_price  stock_quantity  reorder_level  status
0     5751.19             -50             29  Active
1      866.61             266            -10  Active
==================================================

In [40]:
test_df = products_df.copy()

test_df.loc[0,"brand"] = None
test_df.loc[1,"cost_price"] = 90000
test_df.loc[2,"category"] = "Toys"
test_df.loc[3,"stock_quantity"] = -10

In [41]:
validators.run_product_validations(test_df)

############################################################
PRODUCT VALIDATION PIPELINE STARTED
############################################################
==================================================
Product Missing Value Validation
==================================================
❌ Missing values detected:
brand    1
dtype: int64

==================================================
Checking Duplicate SKU
✅ No duplicate SKU found
==================================================
==================================================
Checking Duplicate Product ID
✅ No duplicate product_id found
==================================================
==================================================
Checking Price Validation
❌ Invalid price relationship found
   product_id         sku  product_name category    brand  unit_price  \
1           2  BOO-000002  Data Science    Books  Penguin     1063.59

   cost_price  stock_quantity  reorder_level  status
1     90000.0             266             49  Active
==================================================
==================================================
Checking Product Categories
❌ Invalid categories found
   product_id         sku product_name category brand  unit_price  cost_price  \
2           3  GRO-000003         Milk     Toys  Amul      700.27      493.07

   stock_quantity  reorder_level  status
2             442             34  Active
==================================================
==================================================
Checking Product Status
✅ All statuses are valid
==================================================
==================================================
Checking Stock Validation
❌ Invalid stock values found
   product_id         sku  product_name   category     brand  unit_price  \
3           4  FUR-000004  Dining Table  Furniture  Nilkamal    58740.21

   cost_price  stock_quantity  reorder_level  status
3    42663.18             -10             35  Active
==================================================
############################################################
PRODUCT VALIDATION PIPELINE COMPLETED
############################################################