In [4]:
import sys
from pathlib import Path

project_python = Path.cwd().parent.resolve()

if str(project_python) not in sys.path:
    sys.path.insert(0, str(project_python))

print(project_python)

C:\Users\Welcome\Desktop\RetailIQ\Python

In [5]:
import importlib
import src.generators as generators

importlib.reload(generators)

In [6]:
generators.generate_products(5)

,product_id,sku,product_name,category,brand,unit_price,cost_price,stock_quantity,reorder_level,status
0,1,FUR-000001,Office Chair,Furniture,IKEA,37626.52,27907.76,480,11,Active
1,2,FUR-000002,Bookshelf,Furniture,IKEA,66802.85,55286.18,115,39,Active
2,3,BOO-000003,Data Science,Books,Pearson,1265.75,1005.24,211,31,Active
3,4,ELE-000004,Laptop,Electronics,Sony,96999.79,77041.02,254,42,Active
4,5,FUR-000005,Study Desk,Furniture,Godrej,7106.35,5575.82,384,10,Active

In [7]:
products_df = generators.generate_products(10)

products_df.head()

,product_id,sku,product_name,category,brand,unit_price,cost_price,stock_quantity,reorder_level,status
0,1,CLO-000001,Hoodie,Clothing,Adidas,5058.33,4019.02,73,21,Active
1,2,GRO-000002,Milk,Groceries,Britannia,1905.52,1529.85,245,11,Active
2,3,GRO-000003,Biscuits,Groceries,Amul,1388.07,1040.16,219,44,Active
3,4,ELE-000004,Smartwatch,Electronics,Apple,93357.06,72085.05,439,35,Active
4,5,ELE-000005,Laptop,Electronics,Apple,48666.32,36208.15,406,44,Active

In [8]:
products_df = generators.generate_products(100)

In [9]:
import importlib
import src.validators as validators

importlib.reload(validators)

print("✅ Validators module loaded successfully")

✅ Validators module loaded successfully

In [10]:
test_df = products_df.copy()

test_df.loc[0, "brand"] = None

validators.validate_product_missing_values(test_df)

==================================================
Product Missing Value Validation
==================================================
❌ Missing values detected:
brand    1
dtype: int64

In [11]:
test_df = products_df.copy()

test_df.loc[5,"sku"] = test_df.loc[0,"sku"]

test_df.loc[10,"product_id"] = test_df.loc[0,"product_id"]

In [12]:
validators.validate_duplicate_sku(test_df)

validators.validate_duplicate_product_id(test_df)

==================================================
Checking Duplicate SKU
❌ Duplicate SKU found
   product_id         sku product_name     category    brand  unit_price  \
5           6  CLO-000001       Tablet  Electronics  Samsung   110826.58

   cost_price  stock_quantity  reorder_level  status
5    84674.33             447             48  Active
==================================================
==================================================
Checking Duplicate Product ID
❌ Duplicate product_id found
    product_id         sku      product_name category    brand  unit_price  \
10           1  BOO-000011  Machine Learning    Books  Pearson     2004.23

    cost_price  stock_quantity  reorder_level  status
10     1475.42              61             36  Active
==================================================

In [13]:
test_df = products_df.copy()

test_df.loc[0,"cost_price"] = 90000
test_df.loc[0,"unit_price"] = 50000

In [14]:
validators.validate_price_columns(test_df)

==================================================
Checking Price Validation
❌ Invalid price relationship found
   product_id         sku product_name  category   brand  unit_price  \
0           1  CLO-000001       Jacket  Clothing  Adidas     50000.0

   cost_price  stock_quantity  reorder_level  status
0     90000.0             325             40  Active
==================================================

In [15]:
test_df = products_df.copy()

test_df.loc[0,"category"] = "Toys"

In [16]:
validators.validate_categories(test_df)

==================================================
Checking Product Categories
❌ Invalid categories found
   product_id         sku product_name category   brand  unit_price  \
0           1  CLO-000001       Jacket     Toys  Adidas     4293.48

   cost_price  stock_quantity  reorder_level  status
0     3756.65             325             40  Active
==================================================

In [17]:
validators.validate_status(products_df)

==================================================
Checking Product Status
✅ All statuses are valid
==================================================

In [18]:
test_df = products_df.copy()

test_df.loc[0,"stock_quantity"] = 200
test_df.loc[0,"status"] = "Out of Stock"

In [19]:
validators.validate_status(test_df)

==================================================
Checking Product Status
❌ Invalid status found
   product_id         sku product_name  category   brand  unit_price  \
0           1  CLO-000001       Jacket  Clothing  Adidas     4293.48

   cost_price  stock_quantity  reorder_level        status
0     3756.65             200             40  Out of Stock
==================================================

In [20]:
test_df = products_df.copy()

test_df.loc[0,"stock_quantity"] = -50
test_df.loc[1,"reorder_level"] = -10

In [21]:
validators.validate_stock(test_df)

==================================================
Checking Stock Validation
❌ Invalid stock values found
   product_id         sku product_name     category   brand  unit_price  \
0           1  CLO-000001       Jacket     Clothing  Adidas     4293.48
1           2  ELE-000002      Monitor  Electronics    Sony    37746.07

   cost_price  stock_quantity  reorder_level  status
0     3756.65             -50             40  Active
1    28647.42             443            -10  Active
==================================================

In [22]:
test_df = products_df.copy()

test_df.loc[0,"brand"] = None
test_df.loc[1,"cost_price"] = 90000
test_df.loc[2,"category"] = "Toys"
test_df.loc[3,"stock_quantity"] = -10

In [23]:
validators.run_product_validations(test_df)

============================================================
PRODUCT VALIDATION PIPELINE STARTED
============================================================
==================================================
Product Missing Value Validation
==================================================
❌ Missing values detected:
brand    1
dtype: int64

==================================================
Checking Duplicate SKU
✅ No duplicate SKU found
==================================================
==================================================
Checking Duplicate Product ID
✅ No duplicate product_id found
==================================================
==================================================
Checking Price Validation
❌ Invalid price relationship found
   product_id         sku product_name     category brand  unit_price  \
1           2  ELE-000002      Monitor  Electronics  Sony    37746.07

   cost_price  stock_quantity  reorder_level  status
1     90000.0             443             18  Active
==================================================
==================================================
Checking Product Categories
❌ Invalid categories found
   product_id         sku product_name category brand  unit_price  cost_price  \
2           3  FUR-000003    Bookshelf     Toys  IKEA    36446.37    30517.41

   stock_quantity  reorder_level  status
2             328             24  Active
==================================================
==================================================
Checking Product Status
✅ All statuses are valid
==================================================
==================================================
Checking Stock Validation
❌ Invalid stock values found
   product_id         sku product_name   category   brand  unit_price  \
3           4  GRO-000004     Biscuits  Groceries  Nestle     1893.64

   cost_price  stock_quantity  reorder_level  status
3     1524.36             -10             42  Active
==================================================

============================================================
PRODUCT VALIDATION PIPELINE COMPLETED
============================================================

In [24]:
import importlib
import src.validators as validators

importlib.reload(validators)

In [25]:
from src.generators import generate_products

products_df = generate_products(1000)

products_df.head()

,product_id,sku,product_name,category,brand,unit_price,cost_price,stock_quantity,reorder_level,status
0,1,FUR-000001,Bookshelf,Furniture,IKEA,23498.56,18040.16,262,18,Active
1,2,FUR-000002,Bookshelf,Furniture,IKEA,79885.35,60023.82,180,30,Active
2,3,CLO-000003,Jeans,Clothing,Adidas,1103.80,856.58,155,44,Active
3,4,ELE-000004,Smartphone,Electronics,HP,78418.02,58972.37,286,19,Active
4,5,FUR-000005,Dining Table,Furniture,Godrej,21683.70,18237.65,237,15,Active

In [26]:
validators.run_product_validations(products_df)

============================================================
PRODUCT VALIDATION PIPELINE STARTED
============================================================
==================================================
Product Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Duplicate SKU
✅ No duplicate SKU found
==================================================
==================================================
Checking Duplicate Product ID
✅ No duplicate product_id found
==================================================
==================================================
Checking Price Validation
✅ All prices are valid
==================================================
==================================================
Checking Product Categories
✅ All categories are valid
==================================================
==================================================
Checking Product Status
✅ All statuses are valid
==================================================
==================================================
Checking Stock Validation
✅ All stock values are valid
==================================================

============================================================
PRODUCT VALIDATION PIPELINE COMPLETED
============================================================

In [27]:
import importlib
import src.exporters as exporters

importlib.reload(exporters)

In [28]:
from src.exporters import export_dataframe

In [29]:
exporters.export_dataframe(products_df, "products.csv")

==================================================
Export Completed Successfully
File: ..\exports\products.csv
==================================================

In [30]:
from src import loaders

In [31]:
import importlib
import src.loaders as loaders

importlib.reload(loaders)

In [32]:
loaders.load_dataframe(
    products_df,
    "products"
)

✅ Loaded 1000 rows into retail.products