In [11]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [12]:
import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

In [13]:
from src.generators import generate_inventory
from src.validators import run_inventory_validations
from src.exporters import export_dataframe
from src.loaders import load_dataframe

ImportError: cannot import name 'export_dataframe' from 'src.exporters' (c:\Users\Welcome\Desktop\RetailIQ\Python\src\exporters.py)

In [14]:
from src.generators import generate_products

products_df = generate_products(1000)

In [15]:
inventory_df = generate_inventory(products_df)

In [16]:
import pandas as pd

products_df = pd.read_csv("../exports/products.csv")

inventory_df = generate_inventory(products_df)

In [17]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Delhi Warehouse,212,33,2026-07-13,True,2026-03-20 10:47:27,2026-07-02 10:47:38
1,2,Chennai Warehouse,234,25,2026-07-11,True,2025-10-16 13:09:11,2026-07-08 00:31:48
2,3,Mumbai Warehouse,14,12,2025-10-06,True,2025-09-27 17:39:39,2026-07-16 10:23:06
3,4,Chennai Warehouse,141,34,2025-12-31,True,2026-01-18 07:31:21,2026-07-15 08:54:55
4,5,Bengaluru Warehouse,12,16,2025-12-29,True,2025-07-16 10:28:38,2026-07-05 19:07:45

In [10]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [10]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [11]:
export_dataframe(
    inventory_df,
    "inventory.csv"
)

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [12]:
load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [13]:
from src.generators import generate_products

products_df = generate_products(1000)

In [14]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [24]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [16]:
from src.generators import generate_products

products_df = generate_products(1000)

In [18]:
from src.generators import generate_inventory

inventory_df = generate_inventory(products_df)

In [18]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [19]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [23]:
from src.exporters import export_dataframe

export_dataframe(inventory_df, "inventory.csv")

ImportError: cannot import name 'export_dataframe' from 'src.exporters' (c:\Users\Welcome\Desktop\RetailIQ\Python\src\exporters.py)

In [25]:
from src.loaders import load_dataframe

load_dataframe(inventory_df, "inventory")

✅ Loaded 1000 rows into retail.inventory

In [26]:
inventory_df = generate_inventory(products_df)

In [27]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Chennai Warehouse,111,49,2026-02-25,True,2025-12-16 04:47:14,2026-06-24 01:27:15
1,2,Chennai Warehouse,450,30,2025-11-20,True,2025-10-06 19:20:50,2026-06-26 08:33:29
2,3,Chennai Warehouse,27,14,2026-01-30,True,2026-04-19 14:51:15,2026-07-13 07:46:40
3,4,Mumbai Warehouse,274,23,2025-09-18,True,2025-09-24 06:47:08,2026-06-20 04:08:28
4,5,Chennai Warehouse,297,33,2025-12-25,True,2026-04-08 11:48:07,2026-07-08 09:51:19

In [28]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [29]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [30]:
inventory_df = generate_inventory(products_df)

In [31]:
from src.exporters import export_dataframe

export_dataframe(
    inventory_df,
    "inventory.csv"
)

ImportError: cannot import name 'export_dataframe' from 'src.exporters' (c:\Users\Welcome\Desktop\RetailIQ\Python\src\exporters.py)

In [28]:
from src.loaders import load_dataframe

load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [29]:
from src.generators import generate_employees

employees_df = generate_employees(100)

In [30]:
employees_df.head()

,first_name,last_name,email,phone,branch,designation,manager_name,hire_date,is_active
0,Hredhaan,Tandon,hredhaan.tandon.300@retailiq.com,6840254577,Coimbatore,Cashier,Karthik Raj,2019-12-23,True
1,Sai,Bedi,sai.bedi.113@retailiq.com,2407198822,Bengaluru,Inventory Executive,Sneha Reddy,2023-01-27,True
2,Unnati,Tara,unnati.tara.328@retailiq.com,3331943278,Delhi,Store Manager,Karthik Raj,2019-07-14,True
3,Vyanjana,Dara,vyanjana.dara.640@retailiq.com,2295093073,Delhi,Branch Manager,Arjun Nair,2016-09-05,True
4,Ridhi,Varughese,ridhi.varughese.424@retailiq.com,8902467005,Chennai,Store Manager,Ravi Kumar,2020-10-05,True

In [31]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    100 non-null    str
 1   last_name     100 non-null    str
 2   email         100 non-null    str
 3   phone         100 non-null    str
 4   branch        100 non-null    str
 5   designation   100 non-null    str
 6   manager_name  100 non-null    str
 7   hire_date     100 non-null    datetime64[s]
 8   is_active     100 non-null    bool
dtypes: bool(1), datetime64[s](1), str(7)
memory usage: 6.5 KB

In [14]:
from src.validators import run_employee_validations

run_employee_validations(employees_df)

NameError: name 'employees_df' is not defined

In [15]:
from pathlib import Path
from src.exporters import export_to_csv

In [21]:
export_to_csv(
    employees_df,
    "employees.csv",
    Path("../data")
)

============================================================
✅ Dataset exported successfully!
📁 File Name : employees.csv
📂 Location  : C:\Users\Welcome\Desktop\RetailIQ\Python\data\employees.csv
============================================================

In [37]:
Path("data")

WindowsPath('data')

In [15]:
from src.generators import generate_employees

employees_df = generate_employees(100)

employees_df.head()

,first_name,last_name,email,phone,branch,designation,manager_name,hire_date,is_active
0,Pooja,Vig,pooja.vig.775@retailiq.com,9017285708,Hyderabad,Inventory Executive,Sneha Reddy,2017-02-03,True
1,Ekapad,Kala,ekapad.kala.459@retailiq.com,7882768130,Coimbatore,Sales Executive,Sneha Reddy,2022-12-14,True
2,Tamanna,Garg,tamanna.garg.994@retailiq.com,2505067828,Bengaluru,Branch Manager,Karthik Raj,2024-07-05,True
3,Oeshi,Chana,oeshi.chana.370@retailiq.com,2429633974,Hyderabad,Regional Manager,Priya Sharma,2024-05-27,True
4,Dipta,Dua,dipta.dua.857@retailiq.com,6438311594,Mumbai,Regional Manager,Sneha Reddy,2022-09-06,True

In [16]:
from src.validators import run_employee_validations

run_employee_validations(employees_df)

Running Employee Validations...

✅ No missing values found.
✅ No duplicate emails found.
✅ No duplicate phone numbers found.
✅ Hire dates are valid.

✅ Employee validation completed.

In [22]:
from src.loaders import load_dataframe

In [23]:
load_dataframe(
    employees_df,
    table_name="employees"
)

✅ Loaded 100 rows into retail.employees

In [20]:
from src.config import DATE_START, DATE_END
from src.generators import generate_date_dimension

date_dimension_df = generate_date_dimension(
    DATE_START,
    DATE_END
)

date_dimension_df.head()

,date_key,full_date,year,quarter,month,month_name,week,day,day_name,is_weekend
0,20220101,2022-01-01,2022,1,1,January,52,1,Saturday,True
1,20220102,2022-01-02,2022,1,1,January,52,2,Sunday,True
2,20220103,2022-01-03,2022,1,1,January,1,3,Monday,False
3,20220104,2022-01-04,2022,1,1,January,1,4,Tuesday,False
4,20220105,2022-01-05,2022,1,1,January,1,5,Wednesday,False

In [22]:
date_dimension_df.shape

(1826, 10)

In [19]:
from src.validators import run_date_validations

run_date_validations(date_dimension_df)

Running Date Dimension Validations...

✅ No missing values found.
✅ No duplicate date keys found.
✅ Date range is valid.

✅ Date Dimension validation completed.

In [24]:
from pathlib import Path
from src.exporters import export_to_csv

export_to_csv(
    date_dimension_df,
    "date_dimension.csv",
    Path("../data")
)

============================================================
✅ Dataset exported successfully!
📁 File Name : date_dimension.csv
📂 Location  : C:\Users\Welcome\Desktop\RetailIQ\Python\data\date_dimension.csv
============================================================

In [25]:
from src.loaders import load_dataframe

load_dataframe(
    date_dimension_df,
    table_name="date_dimension"
)

✅ Loaded 1826 rows into retail.date_dimension

In [3]:
from pathlib import Path

file = Path("../exports/customers.csv")

print(file.exists())
print(file.stat().st_size)

True
94264

In [4]:
import pandas as pd

pd.read_csv("../exports/customers.csv").head()

,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,Teerth,Contractor,Male,68,amammen@example.net,9110605949,Kolhapur,Jharkhand,India,2025-06-02
1,Samesh,Bhagat,Female,18,bhasinaashi@example.net,9361407251,Jamnagar,Punjab,India,2025-03-07
2,Vedika,Nagy,Male,67,arin59@example.com,914493235830,Darbhanga,Tamil Nadu,India,2022-09-23
3,Banjeet,Ram,Male,69,frederickmore@example.org,916986448710,Narasaraopet,Chhattisgarh,India,2022-08-08
4,Krish,Natt,Female,55,sethbaghyawati@example.net,914747182396,Ajmer,Maharashtra,India,2023-09-26

In [37]:
from pathlib import Path

list(Path(".").rglob("customers.csv"))

[]

In [39]:
import pandas as pd

customers_df = pd.read_csv("../exports/customers.csv")
employees_df = pd.read_csv("../exports/employees.csv")
date_dimension_df = pd.read_csv("../exports/date_dimension.csv")

EmptyDataError: No columns to parse from file

In [1]:
from pathlib import Path

file = Path("../exports/customers.csv")

print(file.exists())
print(file.stat().st_size)

True
0

In [2]:
from pathlib import Path

file = Path("../exports/customers.csv")

print(file.exists())
print(file.stat().st_size)

True
0

In [2]:
from pathlib import Path

for file in Path("../exports").glob("*.csv"):
    print(f"{file.name}: {file.stat().st_size} bytes")

customers.csv: 0 bytes
date_dimension.csv: 0 bytes
employees.csv: 0 bytes
inventory.csv: 85960 bytes
orders.csv: 0 bytes
order_items.csv: 0 bytes
products.csv: 72595 bytes