In [3]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [4]:
import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

In [5]:
from src.generators import generate_inventory
from src.validators import run_inventory_validations
from src.exporters import export_dataframe
from src.loaders import load_dataframe

ImportError: cannot import name 'export_dataframe' from 'src.exporters' (c:\Users\Welcome\Desktop\RetailIQ\Python\src\exporters.py)

In [6]:
from src.generators import generate_products

products_df = generate_products(1000)

In [7]:
inventory_df = generate_inventory(products_df)

In [8]:
import pandas as pd

products_df = pd.read_csv("../exports/products.csv")

inventory_df = generate_inventory(products_df)

In [9]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Hyderabad Warehouse,89,31,2026-02-03,True,2025-12-06 08:18:57,2026-07-09 21:22:27
1,2,Bengaluru Warehouse,175,27,2025-11-28,True,2025-12-07 14:02:59,2026-06-27 20:15:57
2,3,Mumbai Warehouse,2,32,2026-07-09,True,2025-10-02 17:54:28,2026-07-10 04:14:33
3,4,Delhi Warehouse,215,14,2026-02-27,True,2026-02-16 23:13:36,2026-07-06 14:44:04
4,5,Bengaluru Warehouse,335,49,2025-12-01,True,2025-08-27 23:07:45,2026-06-24 12:37:29

In [10]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [10]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [11]:
export_dataframe(
    inventory_df,
    "inventory.csv"
)

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [12]:
load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [13]:
from src.generators import generate_products

products_df = generate_products(1000)

In [14]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [10]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [16]:
from src.generators import generate_products

products_df = generate_products(1000)

In [17]:
from src.generators import generate_inventory

inventory_df = generate_inventory(products_df)

In [18]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [11]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [12]:
from src.exporters import export_dataframe

export_dataframe(inventory_df, "inventory.csv")

ImportError: cannot import name 'export_dataframe' from 'src.exporters' (c:\Users\Welcome\Desktop\RetailIQ\Python\src\exporters.py)

In [21]:
from src.loaders import load_dataframe

load_dataframe(inventory_df, "inventory")

✅ Loaded 1000 rows into retail.inventory

In [22]:
inventory_df = generate_inventory(products_df)

In [23]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Bengaluru Warehouse,188,29,2025-12-08,True,2025-10-14 10:14:12,2026-07-09 20:35:48
1,2,Hyderabad Warehouse,199,46,2025-07-20,True,2026-01-06 17:39:44,2026-07-09 22:59:49
2,3,Chennai Warehouse,186,44,2026-04-23,True,2025-08-06 02:12:09,2026-07-07 05:41:03
3,4,Hyderabad Warehouse,54,48,2025-08-04,True,2026-05-28 20:36:24,2026-07-07 15:09:25
4,5,Chennai Warehouse,36,11,2025-12-12,True,2025-09-14 06:50:14,2026-06-18 03:37:55

In [24]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [25]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [26]:
inventory_df = generate_inventory(products_df)

In [27]:
from src.exporters import export_dataframe

export_dataframe(
    inventory_df,
    "inventory.csv"
)

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [28]:
from src.loaders import load_dataframe

load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [29]:
from src.generators import generate_employees

employees_df = generate_employees(100)

In [30]:
employees_df.head()

,first_name,last_name,email,phone,branch,designation,manager_name,hire_date,is_active
0,Hredhaan,Tandon,hredhaan.tandon.300@retailiq.com,6840254577,Coimbatore,Cashier,Karthik Raj,2019-12-23,True
1,Sai,Bedi,sai.bedi.113@retailiq.com,2407198822,Bengaluru,Inventory Executive,Sneha Reddy,2023-01-27,True
2,Unnati,Tara,unnati.tara.328@retailiq.com,3331943278,Delhi,Store Manager,Karthik Raj,2019-07-14,True
3,Vyanjana,Dara,vyanjana.dara.640@retailiq.com,2295093073,Delhi,Branch Manager,Arjun Nair,2016-09-05,True
4,Ridhi,Varughese,ridhi.varughese.424@retailiq.com,8902467005,Chennai,Store Manager,Ravi Kumar,2020-10-05,True

In [31]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    100 non-null    str
 1   last_name     100 non-null    str
 2   email         100 non-null    str
 3   phone         100 non-null    str
 4   branch        100 non-null    str
 5   designation   100 non-null    str
 6   manager_name  100 non-null    str
 7   hire_date     100 non-null    datetime64[s]
 8   is_active     100 non-null    bool
dtypes: bool(1), datetime64[s](1), str(7)
memory usage: 6.5 KB

In [14]:
from src.validators import run_employee_validations

run_employee_validations(employees_df)

NameError: name 'employees_df' is not defined

In [15]:
from pathlib import Path
from src.exporters import export_to_csv

In [21]:
export_to_csv(
    employees_df,
    "employees.csv",
    Path("../data")
)

============================================================
✅ Dataset exported successfully!
📁 File Name : employees.csv
📂 Location  : C:\Users\Welcome\Desktop\RetailIQ\Python\data\employees.csv
============================================================

In [37]:
Path("data")

WindowsPath('data')

In [15]:
from src.generators import generate_employees

employees_df = generate_employees(100)

employees_df.head()

,first_name,last_name,email,phone,branch,designation,manager_name,hire_date,is_active
0,Pooja,Vig,pooja.vig.775@retailiq.com,9017285708,Hyderabad,Inventory Executive,Sneha Reddy,2017-02-03,True
1,Ekapad,Kala,ekapad.kala.459@retailiq.com,7882768130,Coimbatore,Sales Executive,Sneha Reddy,2022-12-14,True
2,Tamanna,Garg,tamanna.garg.994@retailiq.com,2505067828,Bengaluru,Branch Manager,Karthik Raj,2024-07-05,True
3,Oeshi,Chana,oeshi.chana.370@retailiq.com,2429633974,Hyderabad,Regional Manager,Priya Sharma,2024-05-27,True
4,Dipta,Dua,dipta.dua.857@retailiq.com,6438311594,Mumbai,Regional Manager,Sneha Reddy,2022-09-06,True

In [16]:
from src.validators import run_employee_validations

run_employee_validations(employees_df)

Running Employee Validations...

✅ No missing values found.
✅ No duplicate emails found.
✅ No duplicate phone numbers found.
✅ Hire dates are valid.

✅ Employee validation completed.

In [22]:
from src.loaders import load_dataframe

In [23]:
load_dataframe(
    employees_df,
    table_name="employees"
)

✅ Loaded 100 rows into retail.employees

In [20]:
from src.config import DATE_START, DATE_END
from src.generators import generate_date_dimension

date_dimension_df = generate_date_dimension(
    DATE_START,
    DATE_END
)

date_dimension_df.head()

,date_key,full_date,year,quarter,month,month_name,week,day,day_name,is_weekend
0,20220101,2022-01-01,2022,1,1,January,52,1,Saturday,True
1,20220102,2022-01-02,2022,1,1,January,52,2,Sunday,True
2,20220103,2022-01-03,2022,1,1,January,1,3,Monday,False
3,20220104,2022-01-04,2022,1,1,January,1,4,Tuesday,False
4,20220105,2022-01-05,2022,1,1,January,1,5,Wednesday,False

In [22]:
date_dimension_df.shape

(1826, 10)

In [19]:
from src.validators import run_date_validations

run_date_validations(date_dimension_df)

Running Date Dimension Validations...

✅ No missing values found.
✅ No duplicate date keys found.
✅ Date range is valid.

✅ Date Dimension validation completed.

In [24]:
from pathlib import Path
from src.exporters import export_to_csv

export_to_csv(
    date_dimension_df,
    "date_dimension.csv",
    Path("../data")
)

============================================================
✅ Dataset exported successfully!
📁 File Name : date_dimension.csv
📂 Location  : C:\Users\Welcome\Desktop\RetailIQ\Python\data\date_dimension.csv
============================================================

In [25]:
from src.loaders import load_dataframe

load_dataframe(
    date_dimension_df,
    table_name="date_dimension"
)

✅ Loaded 1826 rows into retail.date_dimension