In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [4]:
import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

In [6]:
from src.generators import generate_inventory
from src.validators import run_inventory_validations
from src.exporters import export_dataframe
from src.loaders import load_dataframe

In [7]:
from src.generators import generate_products

products_df = generate_products(1000)

In [6]:
inventory_df = generate_inventory(products_df)

In [8]:
import pandas as pd

products_df = pd.read_csv("../exports/products.csv")

inventory_df = generate_inventory(products_df)

In [9]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Hyderabad Warehouse,64,47,2025-11-26,True,2025-08-20 05:30:58,2026-06-23 16:30:35
1,2,Delhi Warehouse,279,47,2025-07-21,True,2026-03-22 22:47:53,2026-07-16 00:18:18
2,3,Bengaluru Warehouse,236,31,2026-06-30,True,2026-03-16 23:33:03,2026-06-23 02:28:42
3,4,Hyderabad Warehouse,294,27,2026-02-04,True,2025-11-26 12:37:59,2026-06-16 20:54:46
4,5,Hyderabad Warehouse,388,24,2026-02-12,True,2026-03-16 16:01:29,2026-06-27 22:07:19

In [10]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [10]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [11]:
export_dataframe(
    inventory_df,
    "inventory.csv"
)

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [12]:
load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [13]:
from src.generators import generate_products

products_df = generate_products(1000)

In [14]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [15]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [16]:
from src.generators import generate_products

products_df = generate_products(1000)

In [17]:
from src.generators import generate_inventory

inventory_df = generate_inventory(products_df)

In [18]:
inventory_df.head()
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [19]:
from src.validators import run_inventory_validations

run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [20]:
from src.exporters import export_dataframe

export_dataframe(inventory_df, "inventory.csv")

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [21]:
from src.loaders import load_dataframe

load_dataframe(inventory_df, "inventory")

✅ Loaded 1000 rows into retail.inventory

In [22]:
inventory_df = generate_inventory(products_df)

In [23]:
inventory_df.head()

,product_id,warehouse,stock_quantity,reorder_level,last_stock_update,is_active,created_at,updated_at
0,1,Bengaluru Warehouse,188,29,2025-12-08,True,2025-10-14 10:14:12,2026-07-09 20:35:48
1,2,Hyderabad Warehouse,199,46,2025-07-20,True,2026-01-06 17:39:44,2026-07-09 22:59:49
2,3,Chennai Warehouse,186,44,2026-04-23,True,2025-08-06 02:12:09,2026-07-07 05:41:03
3,4,Hyderabad Warehouse,54,48,2025-08-04,True,2026-05-28 20:36:24,2026-07-07 15:09:25
4,5,Chennai Warehouse,36,11,2025-12-12,True,2025-09-14 06:50:14,2026-06-18 03:37:55

In [24]:
inventory_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         1000 non-null   int64
 1   warehouse          1000 non-null   str
 2   stock_quantity     1000 non-null   int64
 3   reorder_level      1000 non-null   int64
 4   last_stock_update  1000 non-null   datetime64[s]
 5   is_active          1000 non-null   bool
 6   created_at         1000 non-null   datetime64[us]
 7   updated_at         1000 non-null   datetime64[us]
dtypes: bool(1), datetime64[s](1), datetime64[us](2), int64(3), str(1)
memory usage: 55.8 KB

In [25]:
run_inventory_validations(inventory_df)

============================================================
INVENTORY VALIDATION PIPELINE STARTED
============================================================
==================================================
Inventory Missing Value Validation
==================================================
✅ No missing values found.

==================================================
Checking Inventory Stock
✅ Inventory stock is valid.
==================================================

============================================================
INVENTORY VALIDATION PIPELINE COMPLETED
============================================================

In [26]:
inventory_df = generate_inventory(products_df)

In [27]:
from src.exporters import export_dataframe

export_dataframe(
    inventory_df,
    "inventory.csv"
)

==================================================
Export Completed Successfully
File: ..\exports\inventory.csv
==================================================

In [28]:
from src.loaders import load_dataframe

load_dataframe(
    inventory_df,
    "inventory"
)

✅ Loaded 1000 rows into retail.inventory

In [29]:
from src.generators import generate_employees

employees_df = generate_employees(100)

In [30]:
employees_df.head()

,first_name,last_name,email,phone,branch,designation,manager_name,hire_date,is_active
0,Hredhaan,Tandon,hredhaan.tandon.300@retailiq.com,6840254577,Coimbatore,Cashier,Karthik Raj,2019-12-23,True
1,Sai,Bedi,sai.bedi.113@retailiq.com,2407198822,Bengaluru,Inventory Executive,Sneha Reddy,2023-01-27,True
2,Unnati,Tara,unnati.tara.328@retailiq.com,3331943278,Delhi,Store Manager,Karthik Raj,2019-07-14,True
3,Vyanjana,Dara,vyanjana.dara.640@retailiq.com,2295093073,Delhi,Branch Manager,Arjun Nair,2016-09-05,True
4,Ridhi,Varughese,ridhi.varughese.424@retailiq.com,8902467005,Chennai,Store Manager,Ravi Kumar,2020-10-05,True

In [31]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    100 non-null    str
 1   last_name     100 non-null    str
 2   email         100 non-null    str
 3   phone         100 non-null    str
 4   branch        100 non-null    str
 5   designation   100 non-null    str
 6   manager_name  100 non-null    str
 7   hire_date     100 non-null    datetime64[s]
 8   is_active     100 non-null    bool
dtypes: bool(1), datetime64[s](1), str(7)
memory usage: 6.5 KB

In [32]:
from src.validators import run_employee_validations

run_employee_validations(employees_df)

Running Employee Validations...

✅ No missing values found.
✅ No duplicate emails found.
✅ No duplicate phone numbers found.
✅ Hire dates are valid.

✅ Employee validation completed.