In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path("../").resolve()))

In [4]:
import pandas as pd
from pathlib import Path

from src.generators import generate_customers
from src.exporters import export_to_csv

In [5]:
from src.database import load_dataframe

ImportError: cannot import name 'load_dataframe' from 'src.database' (C:\Users\Welcome\Desktop\RetailIQ\Python\src\database.py)

In [6]:
from src.generators import generate_customers

customers_df = generate_customers(1000)

customers_df.head()

,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,Damyanti,Parekh,Male,69,fganguly@example.net,+917835720009,Hajipur,Uttarakhand,India,2024-06-27
1,Hiral,Borah,Female,55,tamannadasgupta@example.com,+913128623958,Kolhapur,Nagaland,India,2026-06-08
2,Zaid,Natt,Female,36,orinderbhalla@example.net,5671695711,Patna,Punjab,India,2021-07-29
3,Vrinda,Golla,Female,43,xmannan@example.net,08239119575,Nagaon,Punjab,India,2021-09-26
4,Qabil,Kibe,Male,53,vaidyabhavini@example.com,02232044302,Ujjain,Himachal Pradesh,India,2024-10-19

In [5]:
from src.validators import run_customer_validations

run_customer_validations(customers_df)

==================================================
Running Customer Validation Pipeline
==================================================
==================================================
Missing Value Report
==================================================
first_name    0
last_name     0
gender        0
age           0
email         0
phone         0
city          0
state         0
country       0
join_date     0
dtype: int64
==================================================
Duplicate Email Report
==================================================
✅ No duplicate emails found.
==================================================
Age Validation Report
==================================================
✅ All customer ages are valid.
==================================================
Gender Validation Report
==================================================
✅ All gender values are valid.
==================================================
Checking Future Join Dates...
No Future Join Dates Found.
==================================================
Customer Validation Pipeline Completed
==================================================

In [6]:
load_dataframe(
    customers_df,
    table_name="customers",
    if_exists="append"
)

Loaded 1000 rows into 'customers'.

In [8]:
from src.database import get_engine

In [9]:
import pandas as pd

query = """
SELECT *
FROM retail.customers
LIMIT 5;
"""

df = pd.read_sql(query, get_engine())

df

,customer_id,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,1,Ice,Kutty,Male,22,ice.kutty@example.com,9629137402,Karur,Tamil Nadu,India,2026-07-14
1,2,Rehaan,Deol,Female,27,chatterjeezarna@example.org,09129463103,Mumbai,Kerala,India,2025-10-31
2,3,Leena,Cheema,Female,38,ayaansharma@example.com,+913460355385,Ujjain,Tamil Nadu,India,2025-08-27
3,4,Harinakshi,Gole,Female,26,anamikaroy@example.com,03517890557,Shimoga,West Bengal,India,2024-03-10
4,5,Indira,Zacharia,Female,55,osrivastava@example.com,03743882960,Tiruchirappalli,Karnataka,India,2021-10-07

In [10]:
from src.loaders import load_dataframe
from src.generators import generate_customers

customers_df = generate_customers(10)

load_dataframe(
    customers_df,
    table_name="customers"
)

✅ Loaded 10 rows into retail.customers

In [14]:
import notebook_setup

from src.generators import generate_customers

print("Everything works!")

Everything works!

In [9]:
customers_df.head()

,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,Damyanti,Parekh,Male,69,fganguly@example.net,+917835720009,Hajipur,Uttarakhand,India,2024-06-27
1,Hiral,Borah,Female,55,tamannadasgupta@example.com,+913128623958,Kolhapur,Nagaland,India,2026-06-08
2,Zaid,Natt,Female,36,orinderbhalla@example.net,5671695711,Patna,Punjab,India,2021-07-29
3,Vrinda,Golla,Female,43,xmannan@example.net,08239119575,Nagaon,Punjab,India,2021-09-26
4,Qabil,Kibe,Male,53,vaidyabhavini@example.com,02232044302,Ujjain,Himachal Pradesh,India,2024-10-19

In [10]:
export_to_csv(
    customers_df,
    "customers.csv",
    Path("../exports")
)

============================================================
✅ Dataset exported successfully!
📁 File Name : customers.csv
📂 Location  : C:\Users\Welcome\Desktop\RetailIQ\Python\exports\customers.csv
============================================================

In [12]:
from src.loaders import load_dataframe

In [13]:
import pandas as pd

customers_df = pd.read_csv("../exports/customers.csv")

customers_df.shape

(1000, 10)

In [14]:
load_dataframe(
    customers_df,
    "customers"
)

✅ Loaded 1000 rows into retail.customers