In [13]:
import notebook_setup

import pandas as pd
from src.generators import generate_customers
from src.validators import run_customer_validations

In [3]:
from src.database import load_dataframe

In [4]:
from src.generators import generate_customers

customers_df = generate_customers(1000)

customers_df.head()

,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,Rehaan,Deol,Female,27,chatterjeezarna@example.org,09129463103,Mumbai,Kerala,India,2025-10-31
1,Leena,Cheema,Female,38,ayaansharma@example.com,+913460355385,Ujjain,Tamil Nadu,India,2025-08-27
2,Harinakshi,Gole,Female,26,anamikaroy@example.com,03517890557,Shimoga,West Bengal,India,2024-03-10
3,Indira,Zacharia,Female,55,osrivastava@example.com,03743882960,Tiruchirappalli,Karnataka,India,2021-10-07
4,Gauri,Gaba,Female,31,urmibera@example.com,01482548222,Hosur,Kerala,India,2024-10-20

In [5]:
from src.validators import run_customer_validations

run_customer_validations(customers_df)

==================================================
Running Customer Validation Pipeline
==================================================
==================================================
Missing Value Report
==================================================
first_name    0
last_name     0
gender        0
age           0
email         0
phone         0
city          0
state         0
country       0
join_date     0
dtype: int64
==================================================
Duplicate Email Report
==================================================
✅ No duplicate emails found.
==================================================
Age Validation Report
==================================================
✅ All customer ages are valid.
==================================================
Gender Validation Report
==================================================
✅ All gender values are valid.
==================================================
Checking Future Join Dates...
No Future Join Dates Found.
==================================================
Customer Validation Pipeline Completed
==================================================

In [6]:
load_dataframe(
    customers_df,
    table_name="customers",
    if_exists="append"
)

Loaded 1000 rows into 'customers'.

In [8]:
from src.database import get_engine

In [9]:
import pandas as pd

query = """
SELECT *
FROM retail.customers
LIMIT 5;
"""

df = pd.read_sql(query, get_engine())

df

,customer_id,first_name,last_name,gender,age,email,phone,city,state,country,join_date
0,1,Ice,Kutty,Male,22,ice.kutty@example.com,9629137402,Karur,Tamil Nadu,India,2026-07-14
1,2,Rehaan,Deol,Female,27,chatterjeezarna@example.org,09129463103,Mumbai,Kerala,India,2025-10-31
2,3,Leena,Cheema,Female,38,ayaansharma@example.com,+913460355385,Ujjain,Tamil Nadu,India,2025-08-27
3,4,Harinakshi,Gole,Female,26,anamikaroy@example.com,03517890557,Shimoga,West Bengal,India,2024-03-10
4,5,Indira,Zacharia,Female,55,osrivastava@example.com,03743882960,Tiruchirappalli,Karnataka,India,2021-10-07

In [10]:
from src.loaders import load_dataframe
from src.generators import generate_customers

customers_df = generate_customers(10)

load_dataframe(
    customers_df,
    table_name="customers"
)

✅ Loaded 10 rows into retail.customers

In [14]:
import notebook_setup

from src.generators import generate_customers

print("Everything works!")

Everything works!